### ISSUE TITLE
fix Description column is truncated from left

### ISSUE THREAD

**Issue by hawkeye116477** [collinbarrett/FilterLists#968]
I noticed that some filterlists has truncated text from left.  For example search „KAD".  Seems that occurs only on Chromium browsers.
![Screenshot_20190918_000255](https://user-images.githubusercontent.com/19818572/65082998-aefb9580-d9a7-11e9-988b-752aa20d88fe.png)

**Comment by collinbarrett** [comment]
hmm... likely related to the css [here](https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Web/src/components/listsTable/ListsTable.module.css). I'm not a css guru. If anybody is able to assist, it'd be welcomed.

**Comment by hawkeye116477** [comment]
I have possible fix. You can add:
.ant-table {
word-break: break-word;
}
That will somewhat repair it, but then problem is with Languages column,
![Screenshot_20190918_095740](https://user-images.githubusercontent.com/19818572/65129000-c9ab2a00-d9fa-11e9-9a7c-761df6de4e3f.png)

**Comment by collinbarrett** [comment]
^that seems to fix it. thanks, @hawkeye116477 !

**Comment by collinbarrett** [comment]
ah, the root issue was a branching bug in the component's rendering. ^that should fix it.

**Comment by hawkeye116477** [comment]
@collinbarrett Is that last change already online? If yes, then it doesn't fix that issue.

**Comment by collinbarrett** [comment]
Thanks for double-checking. It is deployed. I don't seem to see the issue any more. Can you confirm again? Send another screenshot if you don't mind. Thanks.

![Untitled](https://user-images.githubusercontent.com/6483057/65378833-dc00be80-dcad-11e9-84a2-2c6a53d68cc0.png)

**Comment by hawkeye116477** [comment]
![Screenshot_20190921_222820](https://user-images.githubusercontent.com/19818572/65378875-2179b780-dcbf-11e9-8285-3e2d8ea19878.png)

**Comment by collinbarrett** [comment]
Ah. I see. It has to do with how wide the viewport is. Hmm.. investigating.

**Comment by collinbarrett** [comment]
Give it another try now when you have a chance and let me know. Thanks.

**Comment by hawkeye116477** [comment]
@collinbarrett Now it's better, but Languages column header look little ugly.
![Screenshot_20190921_225553](https://user-images.githubusercontent.com/19818572/65379094-16c12180-dcc3-11e9-927c-50c0649d5799.png)

**Comment by collinbarrett** [comment]
Thanks. Right, [this](https://github.com/collinbarrett/FilterLists/commit/1a2d1e6300447e71e1639f1d3731770c3e7ba2c9) should've fixed that. Still seeing the "Languages" issue on your end?

**Comment by hawkeye116477** [comment]
@collinbarrett No, now is good :smile:
